### ISSUE TITLE
mobile

### ISSUE THREAD

**Issue by nvhiii** [KhromeM/meddy#10]
### Tasks
- [ ] Patient Onboarding UI
- [ ] Hamburger Drawer UI
- [ ] LLM chat UI
- [ ] Voice Detection UI
- [ ] Setting Page
- [ ] Storing Chats
- [ ] more tba
